hotel/hotel/urls.py
from django.contrib import admin
from django.urls import path
import login.views
import gestion.views
import client.views
import client.views
import gestion.views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('index/', login.views.index),
    path('login/', login.views.login),
    path('signUp/', login.views.signUp),
    path('logout/', login.views.logout),
    # ------------------gestionnaire------------------------------------------------
    path('gestionnaire/', gestion.views.gestionnaire),
    path('gestionnaire/createRessource/', gestion.views.createRessource),
    path('gestionnaire/consulterRes/', gestion.views.consulterRes),
    path('gestionnaire/consulterRes/modifyRessource/', gestion.views.gotoModifyRes),
    path('gestionnaire/modifyRes/', gestion.views.modifyRessource),
    path('gestionnaire/consulterRes/deleteRessource/', gestion.views.deleteRessource),
    path('gestionnaire/consulterRes/creerMeuble/', gestion.views.creerMeuble),
    path('gestionnaire/consulterRes/ajouterMeu/', gestion.views.ajouterMeuble),
    path('gestionnaire/consulterRes/removeMeu/', gestion.views.removeMeuble),
    path('gestionnaire/redirectToSuccessfulAdd/', gestion.views.redirectToSuccessfulAdd),
    path('gestionnaire/consulterClient/', gestion.views.consulterClient),
    path('gestionnaire/listDemandes/', gestion.views.listDemandes),
    path('gestionnaire/listClients/', gestion.views.gotoListClients),
    path('gestionnaire/consulterDemande/', client.views.consulterDemande),
    path('gestionnaire/accepterDemande/', gestion.views.accepterDemande),
    path('gestionnaire/consulterRes/modifMeuble/', gestion.views.modifMeuble),
    path('gestionnaire/consulterRes/deleteMeu/', gestion.views.deleteMeuble),
    path('gestionnaire/consulterRes/consultPlanRessource/', gestion.views.consultPlanRessource),
    path('gestionnaire/consulterRes/consulterDemRes/', gestion.views.consulterDemRes),
    path('gestionnaire/refuserDemande/',gestion.views.refuserDemande),

    # --------------------------client----------------------------------------------
    path('mainPage/', client.views.mainPage),
    path('mainPage/consulterProfile/', client.views.consulterProfile),
    path('mainPage/gotoModifyAccount/', client.views.gotoModifyAccount),
    path('mainPage/modifyCompte/', client.views.modifyCompte),
    path('mainPage/createDemande/', client.views.createDemande),
    path('mainPage/consulterDemande/', client.views.consulterDemande),
    path('mainPage/myDemandes/', client.views.myDemandes),
    path('mainPage/consulterRes/', client.views.consulterRes),
    path('mainPage/consulterRes/consultPlanRessource/', client.views.consultPlanRessource),

    path('deleteDemande/', client.views.deleteDemande),

]

hotel/gestion/models.py
from login.models import *
# Create your models here.
class Meuble(models.Model):
    nom_Meuble =  models.CharField(max_length=32, default="default")
    status = models.CharField(max_length=20, default="bon")


class Ressource(models.Model):
    numero = models.CharField(max_length=32, default="default")
    prix = models.IntegerField(default=0)
    type = models.CharField(max_length=150,default="Standard-Chambre Simple-Non Fumeurs")
    def __unicode__(self):
        return self.numero

class Concerne_Meuble(models.Model):
    ressource = models.ForeignKey(Ressource, default = None, on_delete=models.CASCADE)
    meuble = models.ForeignKey(Meuble, default = None, on_delete=models.CASCADE)



class Plan(models.Model):
    numero = models.IntegerField(default=1)
    createTime = models.DateTimeField(auto_now_add=True,blank=True,null=True)
    checkin = models.DateField()
    checkout = models.DateField()
    nbPerson = models.IntegerField(default=2)
    typeRessource = models.CharField(max_length=150,default="Standard-Chambre Simple-Non Fumeurs")
    owner = models.ForeignKey(Client,on_delete=models.CASCADE)
    status = models.CharField(max_length=20, default="attendu")

class Demande(models.Model):
    numero = models.IntegerField(default=1)
    client = models.ForeignKey(Client,on_delete=models.CASCADE,default=None)
    createTime = models.DateTimeField(auto_now_add=True, blank=True, null=True)
    status = models.CharField(max_length=20, default="attendu")

class DemandePlan(models.Model):
    demande = models.ForeignKey(Demande,on_delete=models.CASCADE,default=None)
    plan = models.ForeignKey(Plan,on_delete=models.CASCADE,default=None)

class PlanRessource(models.Model):
    plan = models.ForeignKey(Plan,on_delete=models.CASCADE,default=None)
    ressource = models.ForeignKey(Ressource,on_delete=models.CASCADE,default=None)

hotel/login/models.py
from django.db import models

# Create your models here.

class Gestionnaire(models.Model):
    login = models.CharField(max_length=32,default='defaut')
    pwd = models.CharField(max_length=20,default='defaut')


class Client(models.Model):
    login = models.CharField(max_length=32,default='defaut')
    pwd = models.CharField(max_length=20,default='defaut')
    nom = models.CharField(max_length=32,default='defaut')
    prenom = models.CharField(max_length=32,default='defaut')
    email = models.EmailField(max_length= 32,default='defaut')
    adresse = models.CharField(max_length=100,null=True,blank=True)
    tel = models.CharField(max_length=32,null=True,blank=True)
    def __unicode__(self):
        return self.login

hotel/templates/clientDemande.html
<!--clientDemande.html-->
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link rel="stylesheet" href="https://cdn.staticfile.org/twitter-bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="/static/js/jquery.min.js"></script>
    <script src="/static/js/popper.js"></script>
    <script src="/static/js/bootstrap.min.js"></script>
    <script src='/static/js/page.js'></script>
    <title>{{user.login}}</title>
</head>
<body>
<div class="container">
    <nav class="navbar navbar-inverse" role="navigation">
        <div class="container-fluid">
            <div class="navbar-header">
                <a class="navbar-brand">Information de {{user.nom}} </a>
            </div>
            <div>
                <ul class="nav navbar-nav">
                    <li>{% if request.session.username == "root" %}
                        <a href="/gestionnaire/listClients/?flag=1" class="text-success">retour</a>
                        {% else %}
                        <a href="/mainPage/" class="text-success">retour</a>
                        {% endif %}
                    </li>
                </ul>
            </div>
        </div>
    </nav>
    {% if info %}
    <div id="alert" class="alert alert-{{infoType}}">{{info}}</div>
    {% endif %}

    <div id="zoneDemande">
        <fieldset>
            <legend>Les informations des demandes</legend>
            <ul class="breadcrumb">
                {% if request.session.username == "root" %}
                {% if flag == "1" %}
                <li class="active">Tout</li>
                {% else %}
                <li><a href="/gestionnaire/consulterClient/?id={{user.id}}&flag=1">Tout</a></li>
                {% endif%}
                {% if flag == "2" %}
                <li class="active">Attendu</li>
                {% else %}
                <li><a href="/gestionnaire/consulterClient/?id={{user.id}}&flag=2">Attendu</a></li>
                {% endif%}
                {% if flag == "3" %}
                <li class="active">Accepte</li>
                {% else %}
                <li><a href="/gestionnaire/consulterClient/?id={{user.id}}&flag=3">Accepte</a></li>
                {% endif%}
                {% else %}
                {% if flag == "1" %}
                <li class="active">Tout</li>
                {% else %}
                <li><a href="/mainPage/myDemandes/?id={{user.id}}&flag=1">Tout</a></li>
                {% endif%}
                {% if flag == "2" %}
                <li class="active">Attendu</li>
                {% else %}
                <li><a href="/mainPage/myDemandes/?id={{user.id}}&flag=2">Attendu</a></li>
                {% endif%}
                {% if flag == "3" %}
                <li class="active">Accepte</li>
                {% else %}
                <li><a href="/mainPage/myDemandes/?id={{user.id}}&flag=3">Accepte</a></li>
                {% endif%}
                {% endif %}
            </ul>
                {% if demandes %}
                <table class="table table-striped">
                    <thead>
                    <tr>
                        <th scope="col">ID</th>
                        <th scope="col">Create Date</th>
                        <th scope="col">Status</th>
                        <th scope="col">Details</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for item in demandes %}
                    <tr>
                        <th scope="row">{{item.numero}}</th>
                        <td>{{item.createTime}}</td>
                        <td>{{item.status}}</td>
                        {% if request.session.username == "root" %}
                        <td><a href="/gestionnaire/consulterDemande/?id={{item.id}}&cd={{user.id}}" class="text-success">Consulter</a></td>
                        {% else %}
                        <td><a href="/mainPage/consulterDemande/?id={{item.id}}&cd={{user.id}}" class="text-success">Consulter</a></td>
                        {% endif %}
                    </tr>
                    {% endfor %}
                    </tbody>
                </table>
                {% endif %}
        </fieldset>

    </div>
</div>
</body>
</html>

hotel/templates/clientRessource.html
<!--clientRessource-->
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta content="width=device-width, initial-scale=1, shrink-to-fit=no" name="viewport">

    <link href="https://cdn.staticfile.org/twitter-bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">
    <script src="/static/js/jquery.min.js"></script>
    <script src="/static/js/popper.js"></script>
    <script src="/static/js/bootstrap.min.js"></script>
    <script src='/static/js/page.js'></script>
    <script src='/static/js/ressource.js'></script>
    <link rel="stylesheet" type="text/css" href="/static/css/ressource.css">
    <title>Plan {{plan.id}}</title>
</head>
<body>
<div class="container">
    <div class='row-fluid'>
        <div id="infoRessource">
            <fieldset>
                <legend>Les informations des ressources</legend>
                <table class="table table-striped">
                    <thead>
                    <tr>
                        <th scope="col">Numéro</th>
                        <th scope="col">Type</th>
                        <th scope="col">Prix</th>
                        <th scope="col">Détail</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for item in res %}
                    <tr>
                        <th scope="row">{{item.numero}}</th>
                        <td>{{item.type}}</td>
                        <td>{{item.prix}}</td>
                        <td>
                        {% if request.session.username == 'root' and cd == '-1' %}
                        <a href="/gestionnaire/consulterRes/?resId={{item.id}}&flag=1&cd=-1&planId={{plan.id}}" class="text-success">
                            Voir les ressources</a>
                        {% elif request.session.username == 'root'%}
                        <a href="/gestionnaire/consulterRes/?resId={{item.id}}&id={{idc}}&flag=1&cd={{cd}}&planId={{plan.id}}"
                           class="text-success">Voir les ressources</a>
                        {% else %}
                        <a href="/mainPage/consulterRes/?resId={{item.id}}&flag=1&id={{request.session.id}}&planId={{plan.id}}"
                           class="text-success">Voir les ressources</a>
                        {% endif %}
                        </td>
                    </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </fieldset>
        </div>
    </div>
</div>


</body>
</html>

hotel/templates/demande.html
<!--demande.html-->
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link rel="stylesheet" href="https://cdn.staticfile.org/twitter-bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="/static/js/jquery.min.js"></script>
    <script src="/static/js/popper.js"></script>
    <script src="/static/js/bootstrap.min.js"></script>
    <script src='/static/js/page.js'></script>
    <title>Demande {{demande.numero}}</title>
</head>
<body>
<div class="container">
    <nav class="navbar navbar-inverse" role="navigation">
        <div class="container-fluid">
            <div class="navbar-header">
                <a class="navbar-brand">Information de demande {{demande.id}} </a>
            </div>
            <div>
                <ul class="nav navbar-nav">
                    <li>
                        <a href="" class="text-success">modifier</a>
                    </li>
                    <li>
                        {% if request.session.username == 'root' and cd == '-1' %}
                        <a href="/deleteDemande/?id={{demande.id}}&cd=-1" class="text-success">supprimer</a>
                        {% elif request.session.username == 'root'%}
                        <a href="/deleteDemande/?id={{demande.id}}&cd={{idc}}" class="text-success">supprimer</a>
                        {% else %}
                        <a href="/deleteDemande/?id={{demande.id}}&cd={{idc}}" class="text-success">supprimer</a>
                        {% endif %}
                    </li>
                    <li>
                        <!--                            Cote gestionnaire listdemande -> demande-->
                        {% if request.session.username == 'root' and cd == '-1' %}
                        <a href="/gestionnaire/listDemandes/?flag=1" class="text-success">retour</a>
                        <!--                            Cote gestionnaire listclient -> clientdemande-->
                        {% elif request.session.username == 'root' %}
                        <a href="/gestionnaire/consulterClient/?id={{idc}}&flag=1" class="text-success">retour</a>
                        <!--                            Cote client mainpage -> clientdemande   -->
                        {% else %}
                        <a href="/mainPage/myDemandes/?id={{request.session.id}}&flag=1" class="text-success">retour</a>
                        {% endif %}
                    </li>
                </ul>
            </div>
        </div>
    </nav>
    {% if info %}
    <div id="alert" class="alert alert-{{infoType}}">{{info}}</div>
    {% endif %}
    <table class="table table-striped">
        <thead>
        <tr>
            <th scope="col">Plan</th>
            <th scope="col">Date de checkin</th>
            <th scope="col">Date de checkout</th>
            <th scope="col">Nomber des personnes</th>
            <th scope="col">Type de ressource</th>
            <th scope="col">Temps de creation</th>
            <th scope="col">Status</th>
            <th scope="col">Opération</th>
        </tr>
        </thead>
        <tbody>
        {% for item in plans %}
        <tr>
            <th scope="row">{{item.numero}}</th>
            <td>{{item.checkin}}</td>
            <td>{{item.checkout}}</td>
            <td>{{item.nbPerson}}</td>
            <td>{{item.typeRessource}}</td>
            <td>{{item.createTime}}</td>
            <td>{{item.status}}</td>

            <td>{% if item.status == 'accepte'%}
                    {% if request.session.username == 'root' and cd == '-1' %}
                    <a href="/gestionnaire/consulterRes/consultPlanRessource/?planId={{item.id}}&flag=1&cd=-1"
                       class="text-success">Voir les ressources</a>
                    {% elif request.session.username == 'root'%}
                    <a href="/gestionnaire/consulterRes/consultPlanRessource/?planId={{item.id}}&id={{idc}}&flag=1&cd={{cd}}"
                       class="text-success">Voir les ressources</a>
                    {% else %}
                    <a href="/mainPage/consulterRes/consultPlanRessource/?planId={{item.id}}&id={{request.session.id}}&flag=1"
                       class="text-success">Voir les ressources</a>
                    {% endif %}
                {% endif %}
            </td>
        </tr>
        {% endfor %}
        </tbody>
    </table>
</div>
</body>
</html>

hotel/templates/gestionnaire.html
<!--gestionnaire.html-->
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://cdn.staticfile.org/twitter-bootstrap/3.3.7/css/bootstrap.min.css">

    <script src="/static/js/jquery.min.js"></script>
    <script src="/static/js/popper.js"></script>
    <script src="/static/js/bootstrap.min.js"></script>
    <script src='/static/js/page.js'></script>
    <title>Gestionnaire</title>
</head>
<body>
<div class="container">
    <nav class="navbar navbar-inverse" role="navigation">
        <div class="container-fluid">
            <div class="navbar-header">
                <a class="navbar-brand">Gestionnaire</a>
            </div>
            <div>
                <ul class="nav navbar-nav">
                    <li role="presentation">
                        <a href="/gestionnaire/">Ressources</a>
                    </li>
                    <li role="presentation">
                        <a href="/gestionnaire/listClients/">Clients</a>
                    </li>
                    <li role="presentation">
                        <a href="/gestionnaire/listDemandes/?flag=1">Demandes</a>
                    </li>
                    <li><a href="/logout/">Déconnexion</a></li>
                </ul>
            </div>
        </div>
    </nav>
    {% if info %}
    <div id="alert" class="alert alert-{{infoType}}">{{info}}</div>
    {% endif %}
    <div id="zoneRessource">
        <div id="createRessource" style="display:none">
            <fieldset>
                <legend>Creer une ressource</legend>
                <form action="/gestionnaire/createRessource/" method="post">{% csrf_token %}
                    <div class="form-group">
                        <label for="id_numero">Numero: </label>
                        <input type="text" name="numero" id="id_numero" class="form-control"
                               placeholder="numero de ressource" required/>
                    </div>
                    <div class="form-group">
                        <label for="id_prix">Prix: </label>
                        <input type="number" name="prix" id="id_prix" class="form-control" placeholder="prix" required/>
                    </div>
                    <div class="form-group">
                        <label>Type: </label>
                        <input name="type" id="id_chambre1" value="Chambre" type="radio" checked>Chambre
                        <input name="type" id="id_SDC1" value="SalleDeConference" type="radio"/>Salle de conference
                    </div>
                    <div id="optionCh1">
                        <div class="form-group">
                            <label for="id_taille">Taille: </label>
                            <select name="taille" id="id_taille" class="form-control" placeholder="type de ressource"
                                    required>
                                <option value="Simple">Chambre Simple</option>
                                <option value="Double">Chambre Double</option>
                                <option value="Famille">Chambre Famille</option>
                            </select>
                        </div>
                        <div class="form-group">
                            <label>Niveau: </label>
                            <select name="niveau" id="id_niveau" class="form-control" placeholder="type de ressource"
                                    required>
                                <option value="Standard">Standard</option>
                                <option value="Premium">Premium</option>
                                <option value="President">President</option>
                            </select>
                        </div>
                        <div class="form-group">
                            <label>Fumeurs: </label>
                            <select name="fumeur" id="id_fumeur" class="form-control" placeholder="type de ressource"
                                    required>
                                <option value="Fumeur">Oui</option>
                                <option value="Non Fumeur">Non</option>
                            </select>
                        </div>
                    </div>
                    <div id="optionSDC1" class="form-group" style="display: none">
                        <label for="id_tailleSDC">Taille: </label>
                        <select name="tailleSDC" id="id_tailleSDC" class="form-control" placeholder="type de ressource"
                                required>
                            <option value="Moyenne">Moyenne (10 personnes)</option>
                            <option value="Grande">Grande (20 personnes)</option>
                            <option value="Petite">Petite (5 personnes)</option>
                        </select>
                    </div>

                    <button id="quitCreation" class="btn btn-primary">Annuler</button>
                    <button type="submit" class="btn btn-primary float-right">Creer</button>
                </form>
            </fieldset>
        </div>

        <div id="infoRessource">
            <fieldset>
                <legend>Les informations des ressources</legend>
                <table class="table table-striped">
                    <thead>
                    <tr>
                        <th scope="col">Numéro</th>
                        <th scope="col">Type</th>
                        <th scope="col">Prix</th>
                        <th scope="col">Détail</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for item in res %}
                    <tr>
                        <th scope="row">{{item.numero}}</th>
                        <td>{{item.type}}</td>
                        <td>{{item.prix}}</td>
                        <td><a href="/gestionnaire/consulterRes/?resId={{item.id}}" class="text-success"> Consulter</a>
                        </td>
                    </tr>
                    {% endfor %}
                    <tr>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td><a id="ModeCreation" class="text-success">Ajouter</a></td>
                    </tr>
                    </tbody>
                </table>
            </fieldset>
        </div>

    </div>


</div>
</body>
</html>

hotel/templates/index.html
<!doctype html>
<html lang="en">
<head>
<!--    index.html-->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link rel="stylesheet" href="https://cdn.staticfile.org/twitter-bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="/static/js/jquery.min.js"></script>
    <script src="/static/js/popper.js"></script>
    <script src="/static/js/bootstrap.min.js"></script>
    <script src='/static/js/page.js'></script>
    <title>login</title>
</head>
<body>
<div class="container">
    <fieldset>
        <legend>Systeme de Gestion Hoteliere</legend>
        {% if info %}
        <div id="alert" class="alert alert-{{infoType}}">{{info}}</div>
        {% endif %}
        <div id="zoneLogin">
            <h3>login</h3>
            <form action="/login/" method="post">{% csrf_token %}
                <div class="form-group">
                    <label for="id_username">username: </label>
                    <input type="text" name="login" class="form-control" id="id_username" placeholder="login" autofocus
                           required/>
                </div>
                <div class="form-group">
                    <label for="id_password">password: </label>
                    <input type="password" name="pwd" class="form-control" id="id_password" placeholder="password"
                           required/>
                </div>
                <button type="submit" class="btn btn-primary float-right">Identifiez-vous</button>
            </form>
            <div id="gotoSignup">
                <span>Have not yet username? click </span>
                <ins id="ModeSignUp" class="text-success">here</ins>
            </div>
        </div>
        <div id="zoneSignUp" style="display:none">
            <h3>sign up</h3>
            <form action="/signUp/" method="post">{% csrf_token %}
                <div class="form-group">
                    <label for="id_nom">Nom: </label>
                    <input type="text" name="nom" class="form-control" id="id_nom" placeholder="nom"
                           required="required"/>
                </div>
                <div class="form-group">
                    <label for="id_prenom">Prenom: </label>
                    <input type="text" name="prenom" class="form-control" id="id_prenom" placeholder="prenom"
                           required="required"/>
                </div>
                <div class="form-group">
                    <label for="id_email">Email: </label>
                    <input type="text" name="email" class="form-control" id="id_email" placeholder="email"
                           required="required"/>
                </div>
                <div class="form-group">
                    <label for="id_pwd">Password: </label>
                    <input type="password" name="pwd" class="form-control" id="id_pwd" placeholder="password"
                           required="required"/>
                </div>
                <div class="form-group">
                    <label for="id_adresse">Adresse: </label>
                    <input type="text" name="adresse" class="form-control" id="id_adresse" placeholder="adresse"/>
                </div>
                <div class="form-group">
                    <label for="id_telephone">Telephone: </label>
                    <input type="text" name="tel" class="form-control" id="id_telephone" placeholder="telphone"/>
                </div>
                <button type="submit" class="btn btn-primary float-right">creer votre compte</button>
            </form>
            <div id="gotoLogin">
                <span>Have got an account?</span>
                <ins id="ModeLogin" class="text-success">go to login</ins>
            </div>
        </div>
    </fieldset>
</div>
</body>
</html>

hotel/templates/listClients.html
<!--listClients.html-->
<!DOCTYPE html>
<html lang="en">
<head>
<!--    listClients.html-->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://cdn.staticfile.org/twitter-bootstrap/3.3.7/css/bootstrap.min.css">

    <script src="/static/js/jquery.min.js"></script>
    <script src="/static/js/popper.js"></script>
    <script src="/static/js/bootstrap.min.js"></script>
    <script src='/static/js/page.js'></script>
    <title>listClients</title>
</head>
<body>
<div class="container">
    <nav class="navbar navbar-inverse" role="navigation">
        <div class="container-fluid">
            <div class="navbar-header">
                <a class="navbar-brand">Gestionnaire</a>
            </div>
            <div>
                <ul class="nav navbar-nav">
                    <li role="presentation">
                        <a href="/gestionnaire/">Ressources</a>
                    </li>
                    <li role="presentation">
                        <a href="/gestionnaire/listClients">Clients</a>
                    </li>
                    <li role="presentation">
                        <a href="/gestionnaire/listDemandes/?flag=1">Demandes</a>
                    </li>
                    <li><a href="/logout/">Déconnexion</a></li>
                </ul>
            </div>
        </div>
    </nav>
    {% if info %}
    <div id="alert" class="alert alert-{{infoType}}">{{info}}</div>
    {% endif %}
    <div id="infoClient">
        <fieldset>
            <legend>Les informations des clients</legend>
            <table class="table table-striped">
                <thead>
                <tr>
                    <th scope="col">Login</th>
                    <th scope="col">Nom</th>
                    <th scope="col">Prénom</th>
                    <th scope="col">Adresse</th>
                    <th scope="col">Tél</th>
                    <th scope="col">Details</th>
                </tr>
                </thead>
                <tbody>
                {% for item in users %}
                <tr>
                    <th scope="row">{{item.login}}</th>
                    <td>{{item.nom}}</td>
                    <td>{{item.prenom}}</td>
                    <td>{{item.adresse}}</td>
                    <td>{{item.tel}}</td>
                    <td><a href="/gestionnaire/consulterClient/?id={{item.id}}&flag=1" class="text-success">
                        Consulter</a></td>
                </tr>
                {% endfor %}

                </tbody>
            </table>
        </fieldset>
    </div>
</div>
</body>
</html>

hotel/templates/ressourcePlan.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta content="width=device-width, initial-scale=1, shrink-to-fit=no" name="viewport">

    <link href="https://cdn.staticfile.org/twitter-bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">
    <script src="/static/js/jquery.min.js"></script>
    <script src="/static/js/popper.js"></script>
    <script src="/static/js/bootstrap.min.js"></script>
    <script src='/static/js/page.js'></script>
    <script src='/static/js/ressource.js'></script>
    <link rel="stylesheet" type="text/css" href="/static/css/ressource.css">
    <title>Les plans concerné de Ressource {{res.nom}} {{res.id}}</title>
</head>
<body>
<div class="container">
    <div class='row-fluid'>
<table class="table table-striped">
    <thead class="thead-dark">
    <tr>
        <h2>Liste Plan Concerné</h2>
        <th>#</th>
        <th>checkin</th>
        <th>checkout</th>
        <th>nbPerson</th>
        <th>typeRessource</th>
        <th>owner</th>
        <th>status</th>
    </tr>
    </thead>
    <tbody>
    {% for item in plans %}
    <tr>
        <td>{{item.numero}}</td>
        <td>{{item.checkin}}</td>
        <td>{{item.checkout}}</td>
        <td>{{item.nbPerson}}</td>
        <td>{{item.typeRessource}}</td>
        <td>{{item.owner.login}}</td>
        <td>{{item.status}}</td>
    </tr>
    {% endfor %}

    </tbody>
</table>
    </div>
</div>
</body>
</html>